# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/kg0r0/oauth2-confidential-client
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -race -cover -coverprofile=coverage.out ./...
      - codecov/upload:
        file: ./coverage.out
